/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  WebSocialShareInput,
} from './types/web-social-share/web-social-share-input';

declare global {
  interface HTMLWebSocialShareElement extends HTMLStencilElement {
    'display': boolean;
    'share': WebSocialShareInput[];
  }
  var HTMLWebSocialShareElement: {
    prototype: HTMLWebSocialShareElement;
    new (): HTMLWebSocialShareElement;
  };
  interface HTMLElementTagNameMap {
    'web-social-share': HTMLWebSocialShareElement;
  }
  interface ElementTagNameMap {
    'web-social-share': HTMLWebSocialShareElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'web-social-share': JSXElements.WebSocialShareAttributes;
    }
  }
  namespace JSXElements {
    export interface WebSocialShareAttributes extends HTMLAttributes {
      'display'?: boolean;
      'share'?: WebSocialShareInput[];
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
