/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WebSocialShareInput } from "./types/web-social-share-input";
export namespace Components {
    interface WebSocialShare {
        /**
          * The share options
         */
        "share": WebSocialShareInput;
        /**
          * Trigger the display, or close, of the action sheet which contains the social-share options
         */
        "show": boolean;
    }
}
declare global {
    interface HTMLWebSocialShareElement extends Components.WebSocialShare, HTMLStencilElement {
    }
    var HTMLWebSocialShareElement: {
        prototype: HTMLWebSocialShareElement;
        new (): HTMLWebSocialShareElement;
    };
    interface HTMLElementTagNameMap {
        "web-social-share": HTMLWebSocialShareElement;
    }
}
declare namespace LocalJSX {
    interface WebSocialShare {
        /**
          * An event triggered when the modal is `closed`
         */
        "onClosed"?: (event: CustomEvent<void>) => void;
        /**
          * The share options
         */
        "share"?: WebSocialShareInput;
        /**
          * Trigger the display, or close, of the action sheet which contains the social-share options
         */
        "show"?: boolean;
    }
    interface IntrinsicElements {
        "web-social-share": WebSocialShare;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "web-social-share": LocalJSX.WebSocialShare & JSXBase.HTMLAttributes<HTMLWebSocialShareElement>;
        }
    }
}
